########## Deployment: hello-app-v1 ##########
apiVersion: apps/v1
kind: Deployment
metadata:
 name: hello-app-v1
spec:
 replicas: 3
 selector:
   matchLabels:
     app: hello-app-v1
 template:
   metadata:
     labels:
       app: hello-app-v1
   spec:
     containers:
      - name: myconsumer
        image: gcr.io/google-samples/hello-app:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
########## Service: hello-app-v1 ##########
apiVersion: v1
kind: Service
metadata:
  name: hello-app-v1-service
spec:
  type: NodePort
  selector:
    app: hello-app-v1
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30600
    name: "helloappnossl"
